# -*- coding: utf-8 -*-
"""Laboratório 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHxwoNVDdKKEpfvU4obr3HzWi9-QN0Ck
"""

import numpy as np

a = 14

def f(x):
  return x**2 - a

b, c = 3, 4

while True:
  m = (b+c)/2

  if f(b) * f(m) < 0:
    c = m
    erro = (f(c) - f(b))/f(c)

  elif f(c) * f(m) < 0:
    b = m

  elif f(b) * f(c)