# -*- coding: utf-8 -*-
"""Laboratório 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwJ9AbQfnHEFeQ_BRrwiQJ0veKNJmPTK

QUESTÃO 1
"""

import numpy as np

n = int(input())
arrayA = [float(input()) for x in range(n**2)]
arrayb = [float(input()) for x in range(n)]
A = np.array(arrayA).reshape((n,n))
b = np.array(arrayb).reshape((n,1))

x = np.zeros_like(b)

for i in range(n):
  soma = 0
  for j in range(i):
    soma = soma + A[i,j] * x[j,0]
  x[i,0] = (b[i,0] - soma) / A[i,i]

somaX = np.sum(x)
print(f'{somaX:.1f}')

"""QUESTÃO 2"""

import numpy as np

n = int(input())
arrayA = [float(input()) for x in range(n**2)]
arrayb = [float(input()) for x in range(n)]
A = np.array(arrayA).reshape((n,n))
b = np.array(arrayb).reshape((n,1))

x = np.zeros_like(b)

for i in range(n, -1, -1):
  soma = 0
  for j in range(i):
    soma = soma + A[i,j] * x[j,0]
  x[i,0] = (b[i,0] - soma) / A[i,i]

somaX = np.sum(x)
print(f'{somaX:.1f}')