# -*- coding: utf-8 -*-
"""Sequências e séries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjZVbJG70VfXmZ1Gh94etH3kTtBMaQl6
"""

import math
import numpy as np
import matplotlib.pyplot as plt

def f(x):
  return x * (-0.85)**x


xg = np.arange(1, 100, 1)
yg = f(xg)
plt.plot(xg, yg, 'purple')
plt.grid()
plt.show()

"""Série harmônica definida como função."""

import numpy as np

def f(x):
  soma = 0
  for i in range(1, x+1):
    soma = soma + 1/i
  return soma

n = int(input())

for i in range(1, n+1):
  print (i, ':', f(i))

n = 31

for i in range(2, n):
  soma = 0
  soma = soma + (2 / (i**2 - 1))
print(soma)

import matplotlib.pyplot as plt
import numpy as np

def f(x):
  return x**(-3/4)

xk = np.arange(1, 22, 1)
yk = f(xk)

plt.plot(xk, yk)

# A função f(x) é decrescente, então f'(x) < 0.